apiVersion: v1
kind: ConfigMap
metadata:
  name: faq-config
  namespace: reloc-dev
data:
  NODE_ENV: "production"
  API_PORT: "3000"
  API_PUBLIC_URL: "http://faq-api.reloc-dev.svc.cluster.local"
  S3_ENDPOINT: "http://faq-minio.reloc-dev.svc.cluster.local:9000"
  S3_REGION: "us-east-1"
  S3_BUCKET: "faqchatbot-staging"
  CORS_EXTRA_ORIGINS: ""
