apiVersion: v1
kind: Secret
metadata:
  name: faq-secrets
  namespace: reloc-dev
type: Opaque
stringData:
  DATABASE_URL: "postgresql://faqchatbot:CHANGE_ME@postgres.reloc-dev.svc.cluster.local:5432/faqchatbot"
  REDIS_URL: "redis://redis.reloc-dev.svc.cluster.local:6379"
  JWT_ACCESS_SECRET: "CHANGE_ME_MIN_16_CHARS"
  JWT_WIDGET_SECRET: "CHANGE_ME_MIN_16_CHARS"
  JWT_REFRESH_SECRET: "CHANGE_ME_MIN_16_CHARS"
  S3_ACCESS_KEY_ID: "CHANGE_ME"
  S3_SECRET_ACCESS_KEY: "CHANGE_ME"
